# Generated by Django 5.2.7 on 2026-01-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': [('create_author', 'Create author')]},
        ),
    ]
