# Generated by Django 5.2.7 on 2026-01-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Add Book'), ('can_change_book', 'Change Book'), ('can_delete_book', 'Detele Book')]},
        ),
    ]
